global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "chatserver"
    scheme: https
    static_configs:
      - targets: ["host.docker.internal:6000"]
    tls_config:
      insecure_skip_verify: true   # DEV APENAS; em produção use um cert confiável/CA

